// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: xai/api/v1/deferred.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of deferred completion request.
type DeferredStatus int32

const (
	// Invalid status.
	DeferredStatus_INVALID_DEFERRED_STATUS DeferredStatus = 0
	// The request has been processed and is available for download.
	DeferredStatus_DONE DeferredStatus = 1
	// The request has been processed but the content has expired and is not
	// available anymore.
	DeferredStatus_EXPIRED DeferredStatus = 2
	// The request is still being processed.
	DeferredStatus_PENDING DeferredStatus = 3
	// The request failed due to an internal service error.
	// The error message is in the `error` field of the response.
	DeferredStatus_FAILED DeferredStatus = 4
)

// Enum value maps for DeferredStatus.
var (
	DeferredStatus_name = map[int32]string{
		0: "INVALID_DEFERRED_STATUS",
		1: "DONE",
		2: "EXPIRED",
		3: "PENDING",
		4: "FAILED",
	}
	DeferredStatus_value = map[string]int32{
		"INVALID_DEFERRED_STATUS": 0,
		"DONE":                    1,
		"EXPIRED":                 2,
		"PENDING":                 3,
		"FAILED":                  4,
	}
)

func (x DeferredStatus) Enum() *DeferredStatus {
	p := new(DeferredStatus)
	*p = x
	return p
}

func (x DeferredStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeferredStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_deferred_proto_enumTypes[0].Descriptor()
}

func (DeferredStatus) Type() protoreflect.EnumType {
	return &file_xai_api_v1_deferred_proto_enumTypes[0]
}

func (x DeferredStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeferredStatus.Descriptor instead.
func (DeferredStatus) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_deferred_proto_rawDescGZIP(), []int{0}
}

// The response from the service, when creating a deferred completion request.
type StartDeferredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of this request. This ID can be used to retrieve completion results
	// later.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *StartDeferredResponse) Reset() {
	*x = StartDeferredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_deferred_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartDeferredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeferredResponse) ProtoMessage() {}

func (x *StartDeferredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_deferred_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeferredResponse.ProtoReflect.Descriptor instead.
func (*StartDeferredResponse) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_deferred_proto_rawDescGZIP(), []int{0}
}

func (x *StartDeferredResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Retrieve the deferred chat request's response with the `request_id` in
// StartDeferredResponse.
type GetDeferredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of this request to get.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *GetDeferredRequest) Reset() {
	*x = GetDeferredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_deferred_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeferredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeferredRequest) ProtoMessage() {}

func (x *GetDeferredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_deferred_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeferredRequest.ProtoReflect.Descriptor instead.
func (*GetDeferredRequest) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_deferred_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeferredRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_xai_api_v1_deferred_proto protoreflect.FileDescriptor

var file_xai_api_v1_deferred_proto_rawDesc = []byte{
	0x0a, 0x19, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x61, 0x69,
	0x5f, 0x61, 0x70, 0x69, 0x22, 0x36, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x2a, 0x5d, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x44,
	0x45, 0x46, 0x45, 0x52, 0x52, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58,
	0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xai_api_v1_deferred_proto_rawDescOnce sync.Once
	file_xai_api_v1_deferred_proto_rawDescData = file_xai_api_v1_deferred_proto_rawDesc
)

func file_xai_api_v1_deferred_proto_rawDescGZIP() []byte {
	file_xai_api_v1_deferred_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_deferred_proto_rawDescData = protoimpl.X.CompressGZIP(file_xai_api_v1_deferred_proto_rawDescData)
	})
	return file_xai_api_v1_deferred_proto_rawDescData
}

var file_xai_api_v1_deferred_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xai_api_v1_deferred_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xai_api_v1_deferred_proto_goTypes = []any{
	(DeferredStatus)(0),           // 0: xai_api.DeferredStatus
	(*StartDeferredResponse)(nil), // 1: xai_api.StartDeferredResponse
	(*GetDeferredRequest)(nil),    // 2: xai_api.GetDeferredRequest
}
var file_xai_api_v1_deferred_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xai_api_v1_deferred_proto_init() }
func file_xai_api_v1_deferred_proto_init() {
	if File_xai_api_v1_deferred_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xai_api_v1_deferred_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StartDeferredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_deferred_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetDeferredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xai_api_v1_deferred_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xai_api_v1_deferred_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_deferred_proto_depIdxs,
		EnumInfos:         file_xai_api_v1_deferred_proto_enumTypes,
		MessageInfos:      file_xai_api_v1_deferred_proto_msgTypes,
	}.Build()
	File_xai_api_v1_deferred_proto = out.File
	file_xai_api_v1_deferred_proto_rawDesc = nil
	file_xai_api_v1_deferred_proto_goTypes = nil
	file_xai_api_v1_deferred_proto_depIdxs = nil
}
