// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: xai/api/v1/documents.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RankingMetric is the metric to use for the search.
// Deprecated: Metric now comes from what is set in the collection creation.
type RankingMetric int32

const (
	RankingMetric_RANKING_METRIC_UNKNOWN           RankingMetric = 0
	RankingMetric_RANKING_METRIC_L2_DISTANCE       RankingMetric = 1
	RankingMetric_RANKING_METRIC_COSINE_SIMILARITY RankingMetric = 2
)

// Enum value maps for RankingMetric.
var (
	RankingMetric_name = map[int32]string{
		0: "RANKING_METRIC_UNKNOWN",
		1: "RANKING_METRIC_L2_DISTANCE",
		2: "RANKING_METRIC_COSINE_SIMILARITY",
	}
	RankingMetric_value = map[string]int32{
		"RANKING_METRIC_UNKNOWN":           0,
		"RANKING_METRIC_L2_DISTANCE":       1,
		"RANKING_METRIC_COSINE_SIMILARITY": 2,
	}
)

func (x RankingMetric) Enum() *RankingMetric {
	p := new(RankingMetric)
	*p = x
	return p
}

func (x RankingMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankingMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_documents_proto_enumTypes[0].Descriptor()
}

func (RankingMetric) Type() protoreflect.EnumType {
	return &file_xai_api_v1_documents_proto_enumTypes[0]
}

func (x RankingMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankingMetric.Descriptor instead.
func (RankingMetric) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{0}
}

// Document search using a combination of keyword and semantic search.
type HybridRetrieval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Overfetch multiplier applied to the requested search limit.
	// When set, fetches (limit * search_multiplier) results from each retrieval method
	// before reranking, then returns the top `limit` results after reranking.
	// Valid range is [1, 100]. Defaults to 1 when unset.
	SearchMultiplier *int32 `protobuf:"varint,1,opt,name=search_multiplier,json=searchMultiplier,proto3,oneof" json:"search_multiplier,omitempty"`
	// Which reranker to use to limit results to the desired value.
	//
	// Types that are assignable to Reranker:
	//
	//	*HybridRetrieval_RerankerModel
	//	*HybridRetrieval_ReciprocalRankFusion
	Reranker isHybridRetrieval_Reranker `protobuf_oneof:"reranker"`
}

func (x *HybridRetrieval) Reset() {
	*x = HybridRetrieval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HybridRetrieval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridRetrieval) ProtoMessage() {}

func (x *HybridRetrieval) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridRetrieval.ProtoReflect.Descriptor instead.
func (*HybridRetrieval) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *HybridRetrieval) GetSearchMultiplier() int32 {
	if x != nil && x.SearchMultiplier != nil {
		return *x.SearchMultiplier
	}
	return 0
}

func (m *HybridRetrieval) GetReranker() isHybridRetrieval_Reranker {
	if m != nil {
		return m.Reranker
	}
	return nil
}

func (x *HybridRetrieval) GetRerankerModel() *RerankerModel {
	if x, ok := x.GetReranker().(*HybridRetrieval_RerankerModel); ok {
		return x.RerankerModel
	}
	return nil
}

func (x *HybridRetrieval) GetReciprocalRankFusion() *ReciprocalRankFusion {
	if x, ok := x.GetReranker().(*HybridRetrieval_ReciprocalRankFusion); ok {
		return x.ReciprocalRankFusion
	}
	return nil
}

type isHybridRetrieval_Reranker interface {
	isHybridRetrieval_Reranker()
}

type HybridRetrieval_RerankerModel struct {
	// Use a reranker model to perform the reranking.
	RerankerModel *RerankerModel `protobuf:"bytes,2,opt,name=reranker_model,json=rerankerModel,proto3,oneof"`
}

type HybridRetrieval_ReciprocalRankFusion struct {
	// Use RRF to perform the reranking.
	ReciprocalRankFusion *ReciprocalRankFusion `protobuf:"bytes,3,opt,name=reciprocal_rank_fusion,json=reciprocalRankFusion,proto3,oneof"`
}

func (*HybridRetrieval_RerankerModel) isHybridRetrieval_Reranker() {}

func (*HybridRetrieval_ReciprocalRankFusion) isHybridRetrieval_Reranker() {}

// Document search using keyword matching (sparse embeddings).
type KeywordRetrieval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional, but always used when doing search across multiple collections.
	Reranker *RerankerModel `protobuf:"bytes,1,opt,name=reranker,proto3,oneof" json:"reranker,omitempty"`
}

func (x *KeywordRetrieval) Reset() {
	*x = KeywordRetrieval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeywordRetrieval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordRetrieval) ProtoMessage() {}

func (x *KeywordRetrieval) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordRetrieval.ProtoReflect.Descriptor instead.
func (*KeywordRetrieval) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *KeywordRetrieval) GetReranker() *RerankerModel {
	if x != nil {
		return x.Reranker
	}
	return nil
}

// Document search using semantic similarity (dense embeddings).
type SemanticRetrieval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional, but always used when doing search across multiple collections.
	Reranker *RerankerModel `protobuf:"bytes,1,opt,name=reranker,proto3,oneof" json:"reranker,omitempty"`
}

func (x *SemanticRetrieval) Reset() {
	*x = SemanticRetrieval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SemanticRetrieval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticRetrieval) ProtoMessage() {}

func (x *SemanticRetrieval) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticRetrieval.ProtoReflect.Descriptor instead.
func (*SemanticRetrieval) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticRetrieval) GetReranker() *RerankerModel {
	if x != nil {
		return x.Reranker
	}
	return nil
}

// Configuration for reciprocal rank fusion (RRF) reranking.
type ReciprocalRankFusion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The RRF constant k used in the reciprocal rank fusion formula. Defaults to 60.
	K *int32 `protobuf:"varint,1,opt,name=k,proto3,oneof" json:"k,omitempty"`
	// Weight for embedding (dense) search results. Should be between 0 and 1. Defaults to 0.5.
	EmbeddingWeight float32 `protobuf:"fixed32,3,opt,name=embedding_weight,json=embeddingWeight,proto3" json:"embedding_weight,omitempty"`
	// Weight for keyword (sparse) search results. Should be between 0 and 1. Defaults to 0.5.
	TextWeight float32 `protobuf:"fixed32,4,opt,name=text_weight,json=textWeight,proto3" json:"text_weight,omitempty"`
}

func (x *ReciprocalRankFusion) Reset() {
	*x = ReciprocalRankFusion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReciprocalRankFusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReciprocalRankFusion) ProtoMessage() {}

func (x *ReciprocalRankFusion) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReciprocalRankFusion.ProtoReflect.Descriptor instead.
func (*ReciprocalRankFusion) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{3}
}

func (x *ReciprocalRankFusion) GetK() int32 {
	if x != nil && x.K != nil {
		return *x.K
	}
	return 0
}

func (x *ReciprocalRankFusion) GetEmbeddingWeight() float32 {
	if x != nil {
		return x.EmbeddingWeight
	}
	return 0
}

func (x *ReciprocalRankFusion) GetTextWeight() float32 {
	if x != nil {
		return x.TextWeight
	}
	return 0
}

// Configuration for model-based reranking.
type RerankerModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The model to use for reranking. Defaults to standard reranker model.
	Model *string `protobuf:"bytes,1,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// Instructions for the reranking model. Defaults to generic reranking instructions.
	Instructions *string `protobuf:"bytes,2,opt,name=instructions,proto3,oneof" json:"instructions,omitempty"`
}

func (x *RerankerModel) Reset() {
	*x = RerankerModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RerankerModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankerModel) ProtoMessage() {}

func (x *RerankerModel) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankerModel.ProtoReflect.Descriptor instead.
func (*RerankerModel) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{4}
}

func (x *RerankerModel) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *RerankerModel) GetInstructions() string {
	if x != nil && x.Instructions != nil {
		return *x.Instructions
	}
	return ""
}

// Message that contains settings needed to do a document search.
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The query to search for which will be embedded using the
	// same embedding model as the one used for the source to query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The source to query.
	Source *DocumentsSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The number of chunks to return.
	// Will always return the top matching chunks.
	// Optional, defaults to 10.
	Limit *int32 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// User-defined instructions to be included in the search query. Defaults to generic search instructions.
	Instructions *string `protobuf:"bytes,5,opt,name=instructions,proto3,oneof" json:"instructions,omitempty"`
	// How to perform the document search. Defaults to HybridRetrieval
	//
	// Types that are assignable to RetrievalMode:
	//
	//	*SearchRequest_HybridRetrieval
	//	*SearchRequest_SemanticRetrieval
	//	*SearchRequest_KeywordRetrieval
	RetrievalMode isSearchRequest_RetrievalMode `protobuf_oneof:"retrieval_mode"`
	// Deprecated: Metric now comes from what is set during collection creation.
	//
	// Deprecated: Marked as deprecated in xai/api/v1/documents.proto.
	RankingMetric *RankingMetric `protobuf:"varint,4,opt,name=ranking_metric,json=rankingMetric,proto3,enum=xai_api.RankingMetric,oneof" json:"ranking_metric,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSource() *DocumentsSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SearchRequest) GetInstructions() string {
	if x != nil && x.Instructions != nil {
		return *x.Instructions
	}
	return ""
}

func (m *SearchRequest) GetRetrievalMode() isSearchRequest_RetrievalMode {
	if m != nil {
		return m.RetrievalMode
	}
	return nil
}

func (x *SearchRequest) GetHybridRetrieval() *HybridRetrieval {
	if x, ok := x.GetRetrievalMode().(*SearchRequest_HybridRetrieval); ok {
		return x.HybridRetrieval
	}
	return nil
}

func (x *SearchRequest) GetSemanticRetrieval() *SemanticRetrieval {
	if x, ok := x.GetRetrievalMode().(*SearchRequest_SemanticRetrieval); ok {
		return x.SemanticRetrieval
	}
	return nil
}

func (x *SearchRequest) GetKeywordRetrieval() *KeywordRetrieval {
	if x, ok := x.GetRetrievalMode().(*SearchRequest_KeywordRetrieval); ok {
		return x.KeywordRetrieval
	}
	return nil
}

// Deprecated: Marked as deprecated in xai/api/v1/documents.proto.
func (x *SearchRequest) GetRankingMetric() RankingMetric {
	if x != nil && x.RankingMetric != nil {
		return *x.RankingMetric
	}
	return RankingMetric_RANKING_METRIC_UNKNOWN
}

type isSearchRequest_RetrievalMode interface {
	isSearchRequest_RetrievalMode()
}

type SearchRequest_HybridRetrieval struct {
	HybridRetrieval *HybridRetrieval `protobuf:"bytes,11,opt,name=hybrid_retrieval,json=hybridRetrieval,proto3,oneof"`
}

type SearchRequest_SemanticRetrieval struct {
	SemanticRetrieval *SemanticRetrieval `protobuf:"bytes,12,opt,name=semantic_retrieval,json=semanticRetrieval,proto3,oneof"`
}

type SearchRequest_KeywordRetrieval struct {
	KeywordRetrieval *KeywordRetrieval `protobuf:"bytes,13,opt,name=keyword_retrieval,json=keywordRetrieval,proto3,oneof"`
}

func (*SearchRequest_HybridRetrieval) isSearchRequest_RetrievalMode() {}

func (*SearchRequest_SemanticRetrieval) isSearchRequest_RetrievalMode() {}

func (*SearchRequest_KeywordRetrieval) isSearchRequest_RetrievalMode() {}

// SearchResponse message contains the results of a document search operation.
// It returns a collection of matching document chunks sorted by relevance score.
type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Collection of document chunks that match the search query, ordered by relevance score
	// from highest to lowest.
	Matches []*SearchMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetMatches() []*SearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// SearchMatch message represents a single document chunk that matches the search query.
// It contains the document ID, chunk ID, content text, and a relevance score indicating
// how well it matches the query.
type SearchMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier of the document that contains the matching chunk.
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// Unique identifier of the specific chunk within the document that matched the search query.
	ChunkId string `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// The actual text content of the matching chunk that can be presented to the user.
	ChunkContent string `protobuf:"bytes,3,opt,name=chunk_content,json=chunkContent,proto3" json:"chunk_content,omitempty"`
	// Score is the score of the chunk, which is determined by the ranking metric.
	// For L2 distance, lower scores indicate better matches. Range is [0, inf).
	// For cosine similarity, higher scores indicate better matches. Range is [0, 1].
	Score float32 `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	// The ID(s) of the collection(s) to which this document belongs.
	CollectionIds []string `protobuf:"bytes,5,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *SearchMatch) Reset() {
	*x = SearchMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatch) ProtoMessage() {}

func (x *SearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatch.ProtoReflect.Descriptor instead.
func (*SearchMatch) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{7}
}

func (x *SearchMatch) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SearchMatch) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SearchMatch) GetChunkContent() string {
	if x != nil {
		return x.ChunkContent
	}
	return ""
}

func (x *SearchMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchMatch) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

// Configuration for a documents sources in search requests.
//
// This message configures a source for search content within documents or collections of documents.
// Those documents must be uploaded through the management API or directly on the xAI console:
// https://console.x.ai.
type DocumentsSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IDs of collections to use.
	CollectionIds []string `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *DocumentsSource) Reset() {
	*x = DocumentsSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_documents_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentsSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentsSource) ProtoMessage() {}

func (x *DocumentsSource) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_documents_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentsSource.ProtoReflect.Descriptor instead.
func (*DocumentsSource) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_documents_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentsSource) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

var File_xai_api_v1_documents_proto protoreflect.FileDescriptor

var file_xai_api_v1_documents_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x61,
	0x69, 0x5f, 0x61, 0x70, 0x69, 0x22, 0xfd, 0x01, 0x0a, 0x0f, 0x48, 0x79, 0x62, 0x72, 0x69, 0x64,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x11, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x0e, 0x72,
	0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0d, 0x72,
	0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x55, 0x0a, 0x16,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f,
	0x66, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61,
	0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x46, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x14, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x46, 0x75, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x42,
	0x14, 0x0a, 0x12, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x10, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x72,
	0x61, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x78, 0x61,
	0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x22,
	0x59, 0x0a, 0x11, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00,
	0x52, 0x08, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x46, 0x75, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x01, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x6b, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x6e,
	0x0a, 0x0d, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x19, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x69, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0f, 0x0a,
	0x0d, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x9f,
	0x04, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x12, 0x45, 0x0a, 0x10,
	0x68, 0x79, 0x62, 0x72, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x48, 0x79, 0x62, 0x72, 0x69, 0x64, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c,
	0x48, 0x00, 0x52, 0x0f, 0x68, 0x79, 0x62, 0x72, 0x69, 0x64, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x61, 0x6c, 0x12, 0x4b, 0x0a, 0x12, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x5f,
	0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74,
	0x69, 0x63, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x11, 0x73,
	0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c,
	0x12, 0x48, 0x0a, 0x11, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x78, 0x61,
	0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x12, 0x46, 0x0a, 0x0e, 0x72, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x42, 0x02, 0x18, 0x01, 0x48, 0x03,
	0x52, 0x0d, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x88,
	0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x07, 0x4a, 0x04, 0x08, 0x07, 0x10, 0x08, 0x4a, 0x04,
	0x08, 0x08, 0x10, 0x09, 0x4a, 0x04, 0x08, 0x09, 0x10, 0x0a, 0x4a, 0x04, 0x08, 0x0a, 0x10, 0x0b,
	0x22, 0x40, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x38, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x73, 0x2a, 0x71, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x41, 0x4e, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x4d,
	0x45, 0x54, 0x52, 0x49, 0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x1e, 0x0a, 0x1a, 0x52, 0x41, 0x4e, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x54, 0x52, 0x49,
	0x43, 0x5f, 0x4c, 0x32, 0x5f, 0x44, 0x49, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12,
	0x24, 0x0a, 0x20, 0x52, 0x41, 0x4e, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x54, 0x52, 0x49,
	0x43, 0x5f, 0x43, 0x4f, 0x53, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x49, 0x4d, 0x49, 0x4c, 0x41, 0x52,
	0x49, 0x54, 0x59, 0x10, 0x02, 0x32, 0x48, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x16, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xai_api_v1_documents_proto_rawDescOnce sync.Once
	file_xai_api_v1_documents_proto_rawDescData = file_xai_api_v1_documents_proto_rawDesc
)

func file_xai_api_v1_documents_proto_rawDescGZIP() []byte {
	file_xai_api_v1_documents_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(file_xai_api_v1_documents_proto_rawDescData)
	})
	return file_xai_api_v1_documents_proto_rawDescData
}

var file_xai_api_v1_documents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xai_api_v1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xai_api_v1_documents_proto_goTypes = []any{
	(RankingMetric)(0),           // 0: xai_api.RankingMetric
	(*HybridRetrieval)(nil),      // 1: xai_api.HybridRetrieval
	(*KeywordRetrieval)(nil),     // 2: xai_api.KeywordRetrieval
	(*SemanticRetrieval)(nil),    // 3: xai_api.SemanticRetrieval
	(*ReciprocalRankFusion)(nil), // 4: xai_api.ReciprocalRankFusion
	(*RerankerModel)(nil),        // 5: xai_api.RerankerModel
	(*SearchRequest)(nil),        // 6: xai_api.SearchRequest
	(*SearchResponse)(nil),       // 7: xai_api.SearchResponse
	(*SearchMatch)(nil),          // 8: xai_api.SearchMatch
	(*DocumentsSource)(nil),      // 9: xai_api.DocumentsSource
}
var file_xai_api_v1_documents_proto_depIdxs = []int32{
	5,  // 0: xai_api.HybridRetrieval.reranker_model:type_name -> xai_api.RerankerModel
	4,  // 1: xai_api.HybridRetrieval.reciprocal_rank_fusion:type_name -> xai_api.ReciprocalRankFusion
	5,  // 2: xai_api.KeywordRetrieval.reranker:type_name -> xai_api.RerankerModel
	5,  // 3: xai_api.SemanticRetrieval.reranker:type_name -> xai_api.RerankerModel
	9,  // 4: xai_api.SearchRequest.source:type_name -> xai_api.DocumentsSource
	1,  // 5: xai_api.SearchRequest.hybrid_retrieval:type_name -> xai_api.HybridRetrieval
	3,  // 6: xai_api.SearchRequest.semantic_retrieval:type_name -> xai_api.SemanticRetrieval
	2,  // 7: xai_api.SearchRequest.keyword_retrieval:type_name -> xai_api.KeywordRetrieval
	0,  // 8: xai_api.SearchRequest.ranking_metric:type_name -> xai_api.RankingMetric
	8,  // 9: xai_api.SearchResponse.matches:type_name -> xai_api.SearchMatch
	6,  // 10: xai_api.Documents.Search:input_type -> xai_api.SearchRequest
	7,  // 11: xai_api.Documents.Search:output_type -> xai_api.SearchResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xai_api_v1_documents_proto_init() }
func file_xai_api_v1_documents_proto_init() {
	if File_xai_api_v1_documents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xai_api_v1_documents_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HybridRetrieval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KeywordRetrieval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SemanticRetrieval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReciprocalRankFusion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RerankerModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SearchMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_documents_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DocumentsSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xai_api_v1_documents_proto_msgTypes[0].OneofWrappers = []any{
		(*HybridRetrieval_RerankerModel)(nil),
		(*HybridRetrieval_ReciprocalRankFusion)(nil),
	}
	file_xai_api_v1_documents_proto_msgTypes[1].OneofWrappers = []any{}
	file_xai_api_v1_documents_proto_msgTypes[2].OneofWrappers = []any{}
	file_xai_api_v1_documents_proto_msgTypes[3].OneofWrappers = []any{}
	file_xai_api_v1_documents_proto_msgTypes[4].OneofWrappers = []any{}
	file_xai_api_v1_documents_proto_msgTypes[5].OneofWrappers = []any{
		(*SearchRequest_HybridRetrieval)(nil),
		(*SearchRequest_SemanticRetrieval)(nil),
		(*SearchRequest_KeywordRetrieval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xai_api_v1_documents_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xai_api_v1_documents_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_documents_proto_depIdxs,
		EnumInfos:         file_xai_api_v1_documents_proto_enumTypes,
		MessageInfos:      file_xai_api_v1_documents_proto_msgTypes,
	}.Build()
	File_xai_api_v1_documents_proto = out.File
	file_xai_api_v1_documents_proto_rawDesc = nil
	file_xai_api_v1_documents_proto_goTypes = nil
	file_xai_api_v1_documents_proto_depIdxs = nil
}
