// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: xai/api/v1/image.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Indicates the level of preprocessing to apply to images that will be fed to
// the model.
type ImageDetail int32

const (
	// Detail level is invalid.
	ImageDetail_DETAIL_INVALID ImageDetail = 0
	// The system will decide the image resolution to use.
	ImageDetail_DETAIL_AUTO ImageDetail = 1
	// The model will process a low-resolution version of the image. This is
	// faster and cheaper (i.e. consumes fewer tokens).
	ImageDetail_DETAIL_LOW ImageDetail = 2
	// The model will process a high-resolution of the image. This is slower and
	// more expensive but will allow the model to attend to more nuanced details
	// in the image.
	ImageDetail_DETAIL_HIGH ImageDetail = 3
)

// Enum value maps for ImageDetail.
var (
	ImageDetail_name = map[int32]string{
		0: "DETAIL_INVALID",
		1: "DETAIL_AUTO",
		2: "DETAIL_LOW",
		3: "DETAIL_HIGH",
	}
	ImageDetail_value = map[string]int32{
		"DETAIL_INVALID": 0,
		"DETAIL_AUTO":    1,
		"DETAIL_LOW":     2,
		"DETAIL_HIGH":    3,
	}
)

func (x ImageDetail) Enum() *ImageDetail {
	p := new(ImageDetail)
	*p = x
	return p
}

func (x ImageDetail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageDetail) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_image_proto_enumTypes[0].Descriptor()
}

func (ImageDetail) Type() protoreflect.EnumType {
	return &file_xai_api_v1_image_proto_enumTypes[0]
}

func (x ImageDetail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageDetail.Descriptor instead.
func (ImageDetail) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{0}
}

// The image format to be returned (base-64 encoded string or a url of
// the image).
type ImageFormat int32

const (
	// Image format is invalid.
	ImageFormat_IMG_FORMAT_INVALID ImageFormat = 0
	// A base-64 encoding of the image.
	ImageFormat_IMG_FORMAT_BASE64 ImageFormat = 1
	// An URL at which the user can download the image.
	ImageFormat_IMG_FORMAT_URL ImageFormat = 2
)

// Enum value maps for ImageFormat.
var (
	ImageFormat_name = map[int32]string{
		0: "IMG_FORMAT_INVALID",
		1: "IMG_FORMAT_BASE64",
		2: "IMG_FORMAT_URL",
	}
	ImageFormat_value = map[string]int32{
		"IMG_FORMAT_INVALID": 0,
		"IMG_FORMAT_BASE64":  1,
		"IMG_FORMAT_URL":     2,
	}
)

func (x ImageFormat) Enum() *ImageFormat {
	p := new(ImageFormat)
	*p = x
	return p
}

func (x ImageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_image_proto_enumTypes[1].Descriptor()
}

func (ImageFormat) Type() protoreflect.EnumType {
	return &file_xai_api_v1_image_proto_enumTypes[1]
}

func (x ImageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFormat.Descriptor instead.
func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{1}
}

// Quality levels for image generation with their corresponding resolutions.
// Currently only supported by grok-imagine models.
type ImageQuality int32

const (
	// Quality is invalid.
	ImageQuality_IMG_QUALITY_INVALID ImageQuality = 0
	// Low quality.
	ImageQuality_IMG_QUALITY_LOW ImageQuality = 1
	// Medium quality: (default).
	ImageQuality_IMG_QUALITY_MEDIUM ImageQuality = 2
	// High quality.
	ImageQuality_IMG_QUALITY_HIGH ImageQuality = 3
)

// Enum value maps for ImageQuality.
var (
	ImageQuality_name = map[int32]string{
		0: "IMG_QUALITY_INVALID",
		1: "IMG_QUALITY_LOW",
		2: "IMG_QUALITY_MEDIUM",
		3: "IMG_QUALITY_HIGH",
	}
	ImageQuality_value = map[string]int32{
		"IMG_QUALITY_INVALID": 0,
		"IMG_QUALITY_LOW":     1,
		"IMG_QUALITY_MEDIUM":  2,
		"IMG_QUALITY_HIGH":    3,
	}
)

func (x ImageQuality) Enum() *ImageQuality {
	p := new(ImageQuality)
	*p = x
	return p
}

func (x ImageQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_image_proto_enumTypes[2].Descriptor()
}

func (ImageQuality) Type() protoreflect.EnumType {
	return &file_xai_api_v1_image_proto_enumTypes[2]
}

func (x ImageQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageQuality.Descriptor instead.
func (ImageQuality) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{2}
}

// Aspect ratio for image generation.
// Only supported by grok-imagine models.
type ImageAspectRatio int32

const (
	// Invalid aspect ratio.
	ImageAspectRatio_IMG_ASPECT_RATIO_INVALID ImageAspectRatio = 0
	// 1:1 aspect ratio (square).
	ImageAspectRatio_IMG_ASPECT_RATIO_1_1 ImageAspectRatio = 1
	// 3:4 aspect ratio (portrait).
	ImageAspectRatio_IMG_ASPECT_RATIO_3_4 ImageAspectRatio = 2
	// 4:3 aspect ratio (landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_4_3 ImageAspectRatio = 3
	// 9:16 aspect ratio (tall portrait).
	ImageAspectRatio_IMG_ASPECT_RATIO_9_16 ImageAspectRatio = 4
	// 16:9 aspect ratio (wide landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_16_9 ImageAspectRatio = 5
	// 2:3 aspect ratio (photo portrait).
	ImageAspectRatio_IMG_ASPECT_RATIO_2_3 ImageAspectRatio = 6
	// 3:2 aspect ratio (photo landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_3_2 ImageAspectRatio = 7
	// Auto aspect ratio (model auto-selects based on prompt).
	// Only supported for image generation with a thinking upsampler.
	ImageAspectRatio_IMG_ASPECT_RATIO_AUTO ImageAspectRatio = 8
	// 9:19.5 aspect ratio (extra tall portrait - phone screens).
	ImageAspectRatio_IMG_ASPECT_RATIO_9_19_5 ImageAspectRatio = 9
	// 19.5:9 aspect ratio (extra wide landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_19_5_9 ImageAspectRatio = 10
	// 9:20 aspect ratio (tall portrait - modern phone screens).
	ImageAspectRatio_IMG_ASPECT_RATIO_9_20 ImageAspectRatio = 11
	// 20:9 aspect ratio (ultra wide landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_20_9 ImageAspectRatio = 12
	// 1:2 aspect ratio (tall portrait).
	ImageAspectRatio_IMG_ASPECT_RATIO_1_2 ImageAspectRatio = 13
	// 2:1 aspect ratio (wide landscape).
	ImageAspectRatio_IMG_ASPECT_RATIO_2_1 ImageAspectRatio = 14
)

// Enum value maps for ImageAspectRatio.
var (
	ImageAspectRatio_name = map[int32]string{
		0:  "IMG_ASPECT_RATIO_INVALID",
		1:  "IMG_ASPECT_RATIO_1_1",
		2:  "IMG_ASPECT_RATIO_3_4",
		3:  "IMG_ASPECT_RATIO_4_3",
		4:  "IMG_ASPECT_RATIO_9_16",
		5:  "IMG_ASPECT_RATIO_16_9",
		6:  "IMG_ASPECT_RATIO_2_3",
		7:  "IMG_ASPECT_RATIO_3_2",
		8:  "IMG_ASPECT_RATIO_AUTO",
		9:  "IMG_ASPECT_RATIO_9_19_5",
		10: "IMG_ASPECT_RATIO_19_5_9",
		11: "IMG_ASPECT_RATIO_9_20",
		12: "IMG_ASPECT_RATIO_20_9",
		13: "IMG_ASPECT_RATIO_1_2",
		14: "IMG_ASPECT_RATIO_2_1",
	}
	ImageAspectRatio_value = map[string]int32{
		"IMG_ASPECT_RATIO_INVALID": 0,
		"IMG_ASPECT_RATIO_1_1":     1,
		"IMG_ASPECT_RATIO_3_4":     2,
		"IMG_ASPECT_RATIO_4_3":     3,
		"IMG_ASPECT_RATIO_9_16":    4,
		"IMG_ASPECT_RATIO_16_9":    5,
		"IMG_ASPECT_RATIO_2_3":     6,
		"IMG_ASPECT_RATIO_3_2":     7,
		"IMG_ASPECT_RATIO_AUTO":    8,
		"IMG_ASPECT_RATIO_9_19_5":  9,
		"IMG_ASPECT_RATIO_19_5_9":  10,
		"IMG_ASPECT_RATIO_9_20":    11,
		"IMG_ASPECT_RATIO_20_9":    12,
		"IMG_ASPECT_RATIO_1_2":     13,
		"IMG_ASPECT_RATIO_2_1":     14,
	}
)

func (x ImageAspectRatio) Enum() *ImageAspectRatio {
	p := new(ImageAspectRatio)
	*p = x
	return p
}

func (x ImageAspectRatio) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageAspectRatio) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_image_proto_enumTypes[3].Descriptor()
}

func (ImageAspectRatio) Type() protoreflect.EnumType {
	return &file_xai_api_v1_image_proto_enumTypes[3]
}

func (x ImageAspectRatio) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageAspectRatio.Descriptor instead.
func (ImageAspectRatio) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{3}
}

// Resolution for image generation.
// Only supported by grok-imagine models.
type ImageResolution int32

const (
	// Invalid resolution.
	ImageResolution_IMG_RESOLUTION_INVALID ImageResolution = 0
	// 1k resolution (~1 megapixel total).
	// Dimensions vary by aspect ratio.
	ImageResolution_IMG_RESOLUTION_1K ImageResolution = 1
	// 2k resolution (~4 megapixel total).
	ImageResolution_IMG_RESOLUTION_2K ImageResolution = 2
)

// Enum value maps for ImageResolution.
var (
	ImageResolution_name = map[int32]string{
		0: "IMG_RESOLUTION_INVALID",
		1: "IMG_RESOLUTION_1K",
		2: "IMG_RESOLUTION_2K",
	}
	ImageResolution_value = map[string]int32{
		"IMG_RESOLUTION_INVALID": 0,
		"IMG_RESOLUTION_1K":      1,
		"IMG_RESOLUTION_2K":      2,
	}
)

func (x ImageResolution) Enum() *ImageResolution {
	p := new(ImageResolution)
	*p = x
	return p
}

func (x ImageResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_image_proto_enumTypes[4].Descriptor()
}

func (ImageResolution) Type() protoreflect.EnumType {
	return &file_xai_api_v1_image_proto_enumTypes[4]
}

func (x ImageResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageResolution.Descriptor instead.
func (ImageResolution) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{4}
}

// Request message for generating an image.
type GenerateImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input prompt to generate an image from.
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Optional input image to perform generations based on.
	Image *ImageUrlContent `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	// Name or alias of the image generation model to be used.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Number of images to generate. Allowed values are [1, 10].
	N *int32 `protobuf:"varint,3,opt,name=n,proto3,oneof" json:"n,omitempty"`
	// An opaque string supplied by the API client (customer) to identify a user.
	// The string will be stored in the logs and can be used in customer service
	// requests to identify certain requests.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// Optional field to specify the image format to return the generated image(s)
	// in. See ImageFormat enum for options.
	Format ImageFormat `protobuf:"varint,11,opt,name=format,proto3,enum=xai_api.ImageFormat" json:"format,omitempty"`
	// Optional aspect ratio for image generation/editing.
	// Only supported by grok-imagine models.
	// Defaults to 1:1 if not specified. Auto is only supported for image generation
	// with a thinking upsampler.
	AspectRatio *ImageAspectRatio `protobuf:"varint,14,opt,name=aspect_ratio,json=aspectRatio,proto3,enum=xai_api.ImageAspectRatio,oneof" json:"aspect_ratio,omitempty"`
	// Optional resolution for image generation/editing.
	// Only supported by grok-imagine models.
	// Defaults to 1k if not specified.
	// When 2k is selected, the image is generated at 1k and upscaled using super-resolution.
	// The final output area is capped at approximately 2048x2048 pixels, with dimensions
	// adjusted to preserve aspect ratio and rounded to multiples of 16.
	Resolution *ImageResolution `protobuf:"varint,15,opt,name=resolution,proto3,enum=xai_api.ImageResolution,oneof" json:"resolution,omitempty"`
	// Optional list of input images for multi-reference image editing.
	// Each image is either an image URL or a base64-encoded version of the image.
	// This field cannot be set together with the `image` field.
	Images []*ImageUrlContent `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImageRequest) GetImage() *ImageUrlContent {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImageRequest) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *GenerateImageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GenerateImageRequest) GetFormat() ImageFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_IMG_FORMAT_INVALID
}

func (x *GenerateImageRequest) GetAspectRatio() ImageAspectRatio {
	if x != nil && x.AspectRatio != nil {
		return *x.AspectRatio
	}
	return ImageAspectRatio_IMG_ASPECT_RATIO_INVALID
}

func (x *GenerateImageRequest) GetResolution() ImageResolution {
	if x != nil && x.Resolution != nil {
		return *x.Resolution
	}
	return ImageResolution_IMG_RESOLUTION_INVALID
}

func (x *GenerateImageRequest) GetImages() []*ImageUrlContent {
	if x != nil {
		return x.Images
	}
	return nil
}

// The response from the image generation models containing the generated image(s).
type ImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of generated images (including relevant metadata).
	Images []*GeneratedImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// The model used to generate the image (ignoring aliases).
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The usage of the request.
	Usage *SamplingUsage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageResponse) GetImages() []*GeneratedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ImageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ImageResponse) GetUsage() *SamplingUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Contains all data related to a generated image.
type GeneratedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The generated image.
	//
	// Types that are assignable to Image:
	//
	//	*GeneratedImage_Base64
	//	*GeneratedImage_Url
	Image isGeneratedImage_Image `protobuf_oneof:"image"`
	// Whether the image generated by the model respects moderation rules.
	// The field will be true if the image respect moderation rules. Otherwise
	// the field will be false and the image field is replaced by a placeholder.
	RespectModeration bool `protobuf:"varint,4,opt,name=respect_moderation,json=respectModeration,proto3" json:"respect_moderation,omitempty"`
}

func (x *GeneratedImage) Reset() {
	*x = GeneratedImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_image_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedImage) ProtoMessage() {}

func (x *GeneratedImage) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_image_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedImage.ProtoReflect.Descriptor instead.
func (*GeneratedImage) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{2}
}

func (m *GeneratedImage) GetImage() isGeneratedImage_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (x *GeneratedImage) GetBase64() string {
	if x, ok := x.GetImage().(*GeneratedImage_Base64); ok {
		return x.Base64
	}
	return ""
}

func (x *GeneratedImage) GetUrl() string {
	if x, ok := x.GetImage().(*GeneratedImage_Url); ok {
		return x.Url
	}
	return ""
}

func (x *GeneratedImage) GetRespectModeration() bool {
	if x != nil {
		return x.RespectModeration
	}
	return false
}

type isGeneratedImage_Image interface {
	isGeneratedImage_Image()
}

type GeneratedImage_Base64 struct {
	// A base-64 encoded string of the image. Provided if user specified `IMG_FORMAT_BASE64` in `format` field of the
	// `GenerateImageRequest` message.
	Base64 string `protobuf:"bytes,1,opt,name=base64,proto3,oneof"`
}

type GeneratedImage_Url struct {
	// A url that points to the generated image. Provided if user specified `IMG_FORMAT_URL` in `format` field of the
	// `GenerateImageRequest` message.
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

func (*GeneratedImage_Base64) isGeneratedImage_Image() {}

func (*GeneratedImage_Url) isGeneratedImage_Image() {}

// Contains data relating to an image that is provided to the model.
type ImageUrlContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is either an image URL or a base64-encoded version of the image.
	// The following image formats are supported: PNG, JPG, and WebP.
	// If an image URL is provided, the image will be downloaded for every API
	// request without being cached. Images are fetched using
	// "XaiImageApiFetch/1.0" user agent, and will timeout after 5 seconds.
	// The image size is limited to 10 MiB. If the image download fails, the API
	// request will fail as well.
	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// The level of pre-processing resolution that will be applied to the image.
	Detail ImageDetail `protobuf:"varint,2,opt,name=detail,proto3,enum=xai_api.ImageDetail" json:"detail,omitempty"`
}

func (x *ImageUrlContent) Reset() {
	*x = ImageUrlContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_image_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageUrlContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUrlContent) ProtoMessage() {}

func (x *ImageUrlContent) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_image_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUrlContent.ProtoReflect.Descriptor instead.
func (*ImageUrlContent) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageUrlContent) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageUrlContent) GetDetail() ImageDetail {
	if x != nil {
		return x.Detail
	}
	return ImageDetail_DETAIL_INVALID
}

var File_xai_api_v1_image_proto protoreflect.FileDescriptor

var file_xai_api_v1_image_proto_rawDesc = []byte{
	0x0a, 0x16, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x16, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x03, 0x0a, 0x14, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x78, 0x61, 0x69, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x11, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x01, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x41, 0x0a, 0x0c, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x78, 0x61,
	0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x48, 0x01, 0x52, 0x0b, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x02, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x6e, 0x42,
	0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4a,
	0x04, 0x08, 0x0d, 0x10, 0x0e, 0x22, 0x84, 0x01, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2c,
	0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x0e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x12,
	0x72, 0x65, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x5c, 0x0a, 0x0f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x78, 0x61, 0x69,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2a, 0x53, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x45, 0x54, 0x41, 0x49,
	0x4c, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x45, 0x54, 0x41, 0x49, 0x4c, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10, 0x03, 0x2a, 0x50, 0x0a,
	0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x12,
	0x49, 0x4d, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4d, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x4d,
	0x41, 0x54, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x36, 0x34, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x4d, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x55, 0x52, 0x4c, 0x10, 0x02, 0x2a,
	0x6a, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x17, 0x0a, 0x13, 0x49, 0x4d, 0x47, 0x5f, 0x51, 0x55, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4d, 0x47, 0x5f,
	0x51, 0x55, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x16, 0x0a,
	0x12, 0x49, 0x4d, 0x47, 0x5f, 0x51, 0x55, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x4d, 0x45, 0x44,
	0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4d, 0x47, 0x5f, 0x51, 0x55, 0x41,
	0x4c, 0x49, 0x54, 0x59, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10, 0x03, 0x2a, 0xa7, 0x03, 0x0a, 0x10,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f,
	0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x5f, 0x31, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4d, 0x47, 0x5f,
	0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x33, 0x5f, 0x34,
	0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54,
	0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x34, 0x5f, 0x33, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15,
	0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x5f, 0x39, 0x5f, 0x31, 0x36, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4d, 0x47, 0x5f, 0x41,
	0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x31, 0x36, 0x5f, 0x39,
	0x10, 0x05, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54,
	0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x32, 0x5f, 0x33, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14,
	0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x5f, 0x33, 0x5f, 0x32, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53,
	0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10,
	0x08, 0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x39, 0x5f, 0x31, 0x39, 0x5f, 0x35, 0x10, 0x09, 0x12, 0x1b,
	0x0a, 0x17, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x5f, 0x31, 0x39, 0x5f, 0x35, 0x5f, 0x39, 0x10, 0x0a, 0x12, 0x19, 0x0a, 0x15, 0x49,
	0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f,
	0x39, 0x5f, 0x32, 0x30, 0x10, 0x0b, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53,
	0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x32, 0x30, 0x5f, 0x39, 0x10,
	0x0c, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x31, 0x5f, 0x32, 0x10, 0x0d, 0x12, 0x18, 0x0a, 0x14, 0x49,
	0x4d, 0x47, 0x5f, 0x41, 0x53, 0x50, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f,
	0x32, 0x5f, 0x31, 0x10, 0x0e, 0x2a, 0x5b, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x4d, 0x47, 0x5f,
	0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4d, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x4f,
	0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x31, 0x4b, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x49,
	0x4d, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x32, 0x4b,
	0x10, 0x02, 0x32, 0x51, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x78, 0x61,
	0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xai_api_v1_image_proto_rawDescOnce sync.Once
	file_xai_api_v1_image_proto_rawDescData = file_xai_api_v1_image_proto_rawDesc
)

func file_xai_api_v1_image_proto_rawDescGZIP() []byte {
	file_xai_api_v1_image_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_xai_api_v1_image_proto_rawDescData)
	})
	return file_xai_api_v1_image_proto_rawDescData
}

var file_xai_api_v1_image_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_xai_api_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xai_api_v1_image_proto_goTypes = []any{
	(ImageDetail)(0),             // 0: xai_api.ImageDetail
	(ImageFormat)(0),             // 1: xai_api.ImageFormat
	(ImageQuality)(0),            // 2: xai_api.ImageQuality
	(ImageAspectRatio)(0),        // 3: xai_api.ImageAspectRatio
	(ImageResolution)(0),         // 4: xai_api.ImageResolution
	(*GenerateImageRequest)(nil), // 5: xai_api.GenerateImageRequest
	(*ImageResponse)(nil),        // 6: xai_api.ImageResponse
	(*GeneratedImage)(nil),       // 7: xai_api.GeneratedImage
	(*ImageUrlContent)(nil),      // 8: xai_api.ImageUrlContent
	(*SamplingUsage)(nil),        // 9: xai_api.SamplingUsage
}
var file_xai_api_v1_image_proto_depIdxs = []int32{
	8, // 0: xai_api.GenerateImageRequest.image:type_name -> xai_api.ImageUrlContent
	1, // 1: xai_api.GenerateImageRequest.format:type_name -> xai_api.ImageFormat
	3, // 2: xai_api.GenerateImageRequest.aspect_ratio:type_name -> xai_api.ImageAspectRatio
	4, // 3: xai_api.GenerateImageRequest.resolution:type_name -> xai_api.ImageResolution
	8, // 4: xai_api.GenerateImageRequest.images:type_name -> xai_api.ImageUrlContent
	7, // 5: xai_api.ImageResponse.images:type_name -> xai_api.GeneratedImage
	9, // 6: xai_api.ImageResponse.usage:type_name -> xai_api.SamplingUsage
	0, // 7: xai_api.ImageUrlContent.detail:type_name -> xai_api.ImageDetail
	5, // 8: xai_api.Image.GenerateImage:input_type -> xai_api.GenerateImageRequest
	6, // 9: xai_api.Image.GenerateImage:output_type -> xai_api.ImageResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_xai_api_v1_image_proto_init() }
func file_xai_api_v1_image_proto_init() {
	if File_xai_api_v1_image_proto != nil {
		return
	}
	file_xai_api_v1_usage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_xai_api_v1_image_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_image_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_image_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GeneratedImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_image_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ImageUrlContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xai_api_v1_image_proto_msgTypes[0].OneofWrappers = []any{}
	file_xai_api_v1_image_proto_msgTypes[2].OneofWrappers = []any{
		(*GeneratedImage_Base64)(nil),
		(*GeneratedImage_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xai_api_v1_image_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xai_api_v1_image_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_image_proto_depIdxs,
		EnumInfos:         file_xai_api_v1_image_proto_enumTypes,
		MessageInfos:      file_xai_api_v1_image_proto_msgTypes,
	}.Build()
	File_xai_api_v1_image_proto = out.File
	file_xai_api_v1_image_proto_rawDesc = nil
	file_xai_api_v1_image_proto_goTypes = nil
	file_xai_api_v1_image_proto_depIdxs = nil
}
