// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: xai/api/v1/sample.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reasons why the model stopped sampling.
type FinishReason int32

const (
	// Invalid reason.
	FinishReason_REASON_INVALID FinishReason = 0
	// The max_len parameter specified on the input is reached.
	FinishReason_REASON_MAX_LEN FinishReason = 1
	// The maximum context length of the model is reached.
	FinishReason_REASON_MAX_CONTEXT FinishReason = 2
	// One of the stop words was found.
	FinishReason_REASON_STOP FinishReason = 3
	// A tool call is included in the response.
	FinishReason_REASON_TOOL_CALLS FinishReason = 4
	// Time limit has been reached.
	FinishReason_REASON_TIME_LIMIT FinishReason = 5
)

// Enum value maps for FinishReason.
var (
	FinishReason_name = map[int32]string{
		0: "REASON_INVALID",
		1: "REASON_MAX_LEN",
		2: "REASON_MAX_CONTEXT",
		3: "REASON_STOP",
		4: "REASON_TOOL_CALLS",
		5: "REASON_TIME_LIMIT",
	}
	FinishReason_value = map[string]int32{
		"REASON_INVALID":     0,
		"REASON_MAX_LEN":     1,
		"REASON_MAX_CONTEXT": 2,
		"REASON_STOP":        3,
		"REASON_TOOL_CALLS":  4,
		"REASON_TIME_LIMIT":  5,
	}
)

func (x FinishReason) Enum() *FinishReason {
	p := new(FinishReason)
	*p = x
	return p
}

func (x FinishReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishReason) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_sample_proto_enumTypes[0].Descriptor()
}

func (FinishReason) Type() protoreflect.EnumType {
	return &file_xai_api_v1_sample_proto_enumTypes[0]
}

func (x FinishReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishReason.Descriptor instead.
func (FinishReason) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_sample_proto_rawDescGZIP(), []int{0}
}

// Request to get a text completion response sampling.
type SampleTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Text prompts to sample on.
	Prompt []string `protobuf:"bytes,1,rep,name=prompt,proto3" json:"prompt,omitempty"`
	// Name or alias of the model to be used.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// The number of completions to create concurrently. A single completion will
	// be generated if the parameter is unset. Each completion is charged at the
	// same rate. You can generate at most 128 concurrent completions.
	N *int32 `protobuf:"varint,8,opt,name=n,proto3,oneof" json:"n,omitempty"`
	// The maximum number of tokens to sample. If unset, the model samples until
	// one of the following stop-conditions is reached:
	// - The context length of the model is exceeded
	// - One of the `stop` sequences has been observed.
	//
	// We recommend choosing a reasonable value to reduce the risk of accidental
	// long-generations that consume many tokens.
	MaxTokens *int32 `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	// A random seed used to make the sampling process deterministic. This is
	// provided in a best-effort basis without guarantee that sampling is 100%
	// deterministic given a seed. This is primarily provided for short-lived
	// testing purposes. Given a fixed request and seed, the answers may change
	// over time as our systems evolve.
	Seed *int32 `protobuf:"varint,11,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	// String patterns that will cause the sampling procedure to stop prematurely
	// when observed.
	// Note that the completion is based on individual tokens and sampling can
	// only terminate at token boundaries. If a stop string is a substring of an
	// individual token, the completion will include the entire token, which
	// extends beyond the stop string.
	// For example, if `stop = ["wor"]` and we prompt the model with "hello" to
	// which it responds with "world", then the sampling procedure will stop after
	// observing the "world" token and the completion will contain
	// the entire world "world" even though the stop string was just "wor".
	// You can provide at most 8 stop strings.
	Stop []string `protobuf:"bytes,12,rep,name=stop,proto3" json:"stop,omitempty"`
	// A number between 0 and 2 used to control the variance of completions.
	// The smaller the value, the more deterministic the model will become. For
	// example, if we sample 1000 answers to the same prompt at a temperature of
	// 0.001, then most of the 1000 answers will be identical. Conversely, if we
	// conduct the same experiment at a temperature of 2, virtually no two answers
	// will be identical. Note that increasing the temperature will cause
	// the model to hallucinate more strongly.
	Temperature *float32 `protobuf:"fixed32,14,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	// A number between 0 and 1 controlling the likelihood of the model to use
	// less-common answers. Recall that the model produces a probability for
	// each token. This means, for any choice of token there are thousands of
	// possibilities to choose from. This parameter controls the "nucleus sampling
	// algorithm". Instead of considering every possible token at every step, we
	// only look at the K tokens who's probabilities exceed `top_p`.
	// For example, if we set `top_p = 0.9`, then the set of tokens we actually
	// sample from, will have a probability mass of at least 90%. In practice,
	// low values will make the model more deterministic.
	TopP *float32 `protobuf:"fixed32,15,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	// Number between -2.0 and 2.0.
	// Positive values penalize new tokens based on their existing frequency in the text so far,
	// decreasing the model's likelihood to repeat the same line verbatim.
	FrequencyPenalty *float32 `protobuf:"fixed32,13,opt,name=frequency_penalty,json=frequencyPenalty,proto3,oneof" json:"frequency_penalty,omitempty"`
	// Whether to return log probabilities of the output tokens or not.
	// If true, returns the log probabilities of each output token returned in the content of message.
	Logprobs bool `protobuf:"varint,5,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
	// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
	// Not supported by grok-3 models.
	PresencePenalty *float32 `protobuf:"fixed32,9,opt,name=presence_penalty,json=presencePenalty,proto3,oneof" json:"presence_penalty,omitempty"`
	// An integer between 0 and 8 specifying the number of most likely tokens to return at each token position,
	// each with an associated log probability.
	// logprobs must be set to true if this parameter is used.
	TopLogprobs *int32 `protobuf:"varint,6,opt,name=top_logprobs,json=topLogprobs,proto3,oneof" json:"top_logprobs,omitempty"`
	// An opaque string supplied by the API client (customer) to identify a user.
	// The string will be stored in the logs and can be used in customer service
	// requests to identify certain requests.
	User string `protobuf:"bytes,17,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SampleTextRequest) Reset() {
	*x = SampleTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleTextRequest) ProtoMessage() {}

func (x *SampleTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleTextRequest.ProtoReflect.Descriptor instead.
func (*SampleTextRequest) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleTextRequest) GetPrompt() []string {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *SampleTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SampleTextRequest) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *SampleTextRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *SampleTextRequest) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *SampleTextRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *SampleTextRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *SampleTextRequest) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *SampleTextRequest) GetFrequencyPenalty() float32 {
	if x != nil && x.FrequencyPenalty != nil {
		return *x.FrequencyPenalty
	}
	return 0
}

func (x *SampleTextRequest) GetLogprobs() bool {
	if x != nil {
		return x.Logprobs
	}
	return false
}

func (x *SampleTextRequest) GetPresencePenalty() float32 {
	if x != nil && x.PresencePenalty != nil {
		return *x.PresencePenalty
	}
	return 0
}

func (x *SampleTextRequest) GetTopLogprobs() int32 {
	if x != nil && x.TopLogprobs != nil {
		return *x.TopLogprobs
	}
	return 0
}

func (x *SampleTextRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Response of a text completion response sampling.
type SampleTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of this request. This ID will also show up on your billing records
	// and you can use it when contacting us regarding a specific request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Completions in response to the input messages. The number of completions is
	// controlled via the `n` parameter on the request.
	Choices []*SampleChoice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	// A UNIX timestamp (UTC) indicating when the response object was created.
	// The timestamp is taken when the model starts generating response.
	Created *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	// The name of the model used for the request. This model name contains
	// the actual model name used rather than any aliases.
	// This means the this can be `grok-2-1212` even when the request was
	// specifying `grok-2-latest`.
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	// Note supported yet. Included for compatibility reasons.
	SystemFingerprint string `protobuf:"bytes,7,opt,name=system_fingerprint,json=systemFingerprint,proto3" json:"system_fingerprint,omitempty"`
	// The number of tokens consumed by this request.
	Usage *SamplingUsage `protobuf:"bytes,9,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *SampleTextResponse) Reset() {
	*x = SampleTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleTextResponse) ProtoMessage() {}

func (x *SampleTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleTextResponse.ProtoReflect.Descriptor instead.
func (*SampleTextResponse) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_sample_proto_rawDescGZIP(), []int{1}
}

func (x *SampleTextResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SampleTextResponse) GetChoices() []*SampleChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *SampleTextResponse) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *SampleTextResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SampleTextResponse) GetSystemFingerprint() string {
	if x != nil {
		return x.SystemFingerprint
	}
	return ""
}

func (x *SampleTextResponse) GetUsage() *SamplingUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Contains the response generated by the model.
type SampleChoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicating why the model stopped sampling.
	FinishReason FinishReason `protobuf:"varint,1,opt,name=finish_reason,json=finishReason,proto3,enum=xai_api.FinishReason" json:"finish_reason,omitempty"`
	// The index of this choice in the list of choices. If you set `n > 1` on
	// your request, you will receive more than one choice in your response.
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The actual text generated by the model.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SampleChoice) Reset() {
	*x = SampleChoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_api_v1_sample_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleChoice) ProtoMessage() {}

func (x *SampleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_sample_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleChoice.ProtoReflect.Descriptor instead.
func (*SampleChoice) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_sample_proto_rawDescGZIP(), []int{2}
}

func (x *SampleChoice) GetFinishReason() FinishReason {
	if x != nil {
		return x.FinishReason
	}
	return FinishReason_REASON_INVALID
}

func (x *SampleChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SampleChoice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_xai_api_v1_sample_proto protoreflect.FileDescriptor

var file_xai_api_v1_sample_proto_rawDesc = []byte{
	0x0a, 0x17, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x61, 0x69, 0x5f, 0x61,
	0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x78, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x04, 0x0a, 0x11,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x11, 0x0a, 0x01, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x01, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x74, 0x6f, 0x70, 0x12, 0x25, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x5f, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52, 0x04, 0x74, 0x6f, 0x70,
	0x50, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x11, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x05, 0x52, 0x10, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x50, 0x65, 0x6e, 0x61,
	0x6c, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f,
	0x62, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f,
	0x62, 0x73, 0x12, 0x2e, 0x0a, 0x10, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70,
	0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x48, 0x06, 0x52, 0x0f,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f,
	0x62, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x07, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x4c,
	0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x04,
	0x0a, 0x02, 0x5f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x42, 0x13, 0x0a, 0x11,
	0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74,
	0x79, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f,
	0x62, 0x73, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x4a, 0x04,
	0x08, 0x10, 0x10, 0x11, 0x4a, 0x04, 0x08, 0x12, 0x10, 0x13, 0x22, 0xfe, 0x01, 0x0a, 0x12, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2d,
	0x0a, 0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74, 0x0a, 0x0c, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x2a, 0x8d, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x4c, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45,
	0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x58, 0x54,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x4f,
	0x50, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x54, 0x4f,
	0x4f, 0x4c, 0x5f, 0x43, 0x41, 0x4c, 0x4c, 0x53, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45,
	0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10,
	0x05, 0x32, 0xa5, 0x01, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x47, 0x0a, 0x0a,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x2e, 0x78, 0x61, 0x69,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x78,
	0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x78, 0x61, 0x69, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_xai_api_v1_sample_proto_rawDescOnce sync.Once
	file_xai_api_v1_sample_proto_rawDescData = file_xai_api_v1_sample_proto_rawDesc
)

func file_xai_api_v1_sample_proto_rawDescGZIP() []byte {
	file_xai_api_v1_sample_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_xai_api_v1_sample_proto_rawDescData)
	})
	return file_xai_api_v1_sample_proto_rawDescData
}

var file_xai_api_v1_sample_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xai_api_v1_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xai_api_v1_sample_proto_goTypes = []any{
	(FinishReason)(0),             // 0: xai_api.FinishReason
	(*SampleTextRequest)(nil),     // 1: xai_api.SampleTextRequest
	(*SampleTextResponse)(nil),    // 2: xai_api.SampleTextResponse
	(*SampleChoice)(nil),          // 3: xai_api.SampleChoice
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*SamplingUsage)(nil),         // 5: xai_api.SamplingUsage
}
var file_xai_api_v1_sample_proto_depIdxs = []int32{
	3, // 0: xai_api.SampleTextResponse.choices:type_name -> xai_api.SampleChoice
	4, // 1: xai_api.SampleTextResponse.created:type_name -> google.protobuf.Timestamp
	5, // 2: xai_api.SampleTextResponse.usage:type_name -> xai_api.SamplingUsage
	0, // 3: xai_api.SampleChoice.finish_reason:type_name -> xai_api.FinishReason
	1, // 4: xai_api.Sample.SampleText:input_type -> xai_api.SampleTextRequest
	1, // 5: xai_api.Sample.SampleTextStreaming:input_type -> xai_api.SampleTextRequest
	2, // 6: xai_api.Sample.SampleText:output_type -> xai_api.SampleTextResponse
	2, // 7: xai_api.Sample.SampleTextStreaming:output_type -> xai_api.SampleTextResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_xai_api_v1_sample_proto_init() }
func file_xai_api_v1_sample_proto_init() {
	if File_xai_api_v1_sample_proto != nil {
		return
	}
	file_xai_api_v1_usage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_xai_api_v1_sample_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SampleTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_sample_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SampleTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_api_v1_sample_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SampleChoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xai_api_v1_sample_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xai_api_v1_sample_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xai_api_v1_sample_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_sample_proto_depIdxs,
		EnumInfos:         file_xai_api_v1_sample_proto_enumTypes,
		MessageInfos:      file_xai_api_v1_sample_proto_msgTypes,
	}.Build()
	File_xai_api_v1_sample_proto = out.File
	file_xai_api_v1_sample_proto_rawDesc = nil
	file_xai_api_v1_sample_proto_goTypes = nil
	file_xai_api_v1_sample_proto_depIdxs = nil
}
